### ISSUE TITLE
Extensions repo has been DMCAed

### ISSUE THREAD

**Issue by mirh** [Onestay/CR-Unblocker-Server#1]
Supposedly, due to file: `/src/background_script.js`
Is it too hard to object the thing if wrong, or adjust the script a bit otherwise?

**Comment by onestay** [comment]
I'm aware of this. What's written in the text is wrong and the source code is entirely written by contributors and me however the dmca law also says that you can send a dmca request to programs which circumvents access restrictions to copyrighted content which the extension kinda does. I would file a counternotice if 100% sure that I don't get into legal trouble.

**Comment by Blightwidow** [comment]
Do we still have the source code at least ? 

I am surprise they went after the repo instead of the extensions. 

Concerning their right to emit such notice, it is hard to say. We would need the help from a lawyer. Maybe a mail to the EFF or something but frankly I don’t think we stand a lot of chance

**Comment by Blightwidow** [comment]
Also just read the notice and yeah there request are totally bogus. The script access an API and none of the script was taken from Crunhyroll source code that we don’t have access to anyway.

**Comment by 999eagle** [comment]
@Blightwidow we still have the code. I've create a private repository containing the code as I wrote in our Slack :)

**Comment by onestay** [comment]
Yea the request doesn't make sense. Not sure why they wrote it like that. However I can see the reason for the dmca. And it wonders me too that they didn't dmca the extension.

**Comment by mirh** [comment]
@KolbyClark what about your bgp.js instead?

**Comment by KolbyClark** [comment]
@mirh I'm in the same sort of position. My code was all written by me and while I do consume an API that CR uses for their apps, that shouldn't really count. Nevertheless I contacted CR and the head of CS said "we can't give permission to post the source code" which is odd, since it is my code and I wouldn't need their permission to post anything. It is pretty stupid but I also didn't want to risk legal trouble by fighting it, so I just deleted my repo.

**Comment by mirh** [comment]
[Those](https://github.com/github/dmca/blob/master/2018/2018-03-26-CrunchyRoll.md) dudes seem [pretty](https://anime.frikafrax.com/2015/10-3255/remove-your-media-llc-uses-inaccurate-evidence.html) keen [with](https://www.techdirt.com/articles/20140711/11114227854/us-film-distributor-copyright-enforcement-company-join-forces-to-kick-creative-commons-licensed-film-off-youtube.shtml) wrong [notices](https://torrentfreak.com/anti-piracy-group-reveals-personal-details-of-counter-notice-senders-160730/) tbh.

**Comment by Blightwidow** [comment]
Classic not flagging wrong content and blackmail

**Comment by onestay** [comment]
"Apparently, the only evaluation Remove Your Media LLC performed was to look for similarities in page titles and URLs without evaluating the actual page content and felt that was adequate for evidence of copyright infringement." That definitely seems super shady. I'll go ask some people that know more about this than I do.

**Comment by Dunky13** [comment]
Any updates on this by any chance?
