### ISSUE TITLE
Doesn't work anymore (again)

### ISSUE THREAD

**Issue by 60percentCaffeine** [Onestay/CR-Unblocker-Server#7]
Crunchyroll changed something again and the extension stopped working... again. The page keeps refreshing.

If it's impossible to fix, please leave the login saving working. It's really convenient.

**Comment by kutyel** [comment]
It's true, since yesterday it causes a weird refresh every few seconds, let me know if I can help I'm also a frontend developer 😉 thanks for the extension btw I love it and it's literally the only reason why I still pay crunchyroll! 😘

**Comment by onestay** [comment]
I currently have no time whatsoever to investigate this issue/to maintain the extension

**Comment by 999eagle** [comment]
So I've investigated the current state of CR-Unblocker and it seems like Crunchyroll changed something on their end which stops our workaround. We still get a session id with US country code, but Crunchyroll still recognizes the original country even after setting the cookie. I'll investigate further and try to find another workaround.

**Comment by 999eagle** [comment]
Okay for now I've tried using a VPN to definitely get a US session and then using the same cookies without VPN. Sadly Crunchyroll switches back to my region without changing the cookies.
It looks like CR actually checks the country on each request now instead of just when starting a session, so the whole idea behind this extension won't work anymore. I'll keep looking into it for the next few weeks, but if CR doesn't change anything on their website, the extension sadly will not work anymore.

**Comment by kagesenshi** [comment]
@999eagle 

i found a workaround when trying to add proxy support into kodi crunchyroll in order to get around this .. i noticed that the video url to the m3u8 file itself remains working in my region .. but every other API request need to be proxied through US .. so this plugin need to support proxying the API request all the way until getting the m3u8 URL.

**Comment by kutyel** [comment]
Suddenly the extension works again, thanks all! 🥳
